import Head from 'next/head'
import {Inter} from 'next/font/google'
import styled from "styled-components";

const inter = Inter({subsets: ['latin']})

export default function Home() {
    return (
        <HomeContainer>
            <Head>
                <title>Your Name</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HeadingMd>
                <p>[Your Self Introduction]</p>
                <p>
                    (This is a website)
                </p>
            </HeadingMd>
            <HeadingMd padding={1}>
                <HeadingLarge>Blog</HeadingLarge>
                <List>

                </List>
            </HeadingMd>
        </HomeContainer>
    )
}

const HomeContainer = styled.div`
  padding: 0 2rem;
`;

const HeadingMd = styled.section<{ padding?: number }>`
  font-size: 1.2rem;
  line-height: 1.5;
  padding: ${(props) => props.padding ? `${props.padding}px` : 0};
`

const HeadingLarge = styled.h2`
  font-size: 1.5rem;
  line-height: 1.4;
  margin: 1rem 0;
`

const List = styled.ul`
  list-style: none;
  padding: 0;
  margin: 0;
`