import './globals.css'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import StyledComponentsRegistry from "@/lib/registry";
import React from "react";
import Link from "next/link";

const roboto = localFont({
  src: '../font/roboto.woff2',
  weight: '400'
})


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <StyledComponentsRegistry>
      <body className={roboto.className}>
      <nav>
        <Link href={"/"}>
        Home
        </Link>
        &nbsp;&nbsp;
        <Link href={"/posts"}>
          Post
        </Link>
      </nav>

      <main>
      {children}
      </main>
      </body>
    </StyledComponentsRegistry>
    </html>
  )
}
